CREATE TABLE Notes (
    NoteID INT PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Content TEXT,
    UserID INT REFERENCES Users(UserID),
    FolderID INT REFERENCES Folders(FolderID),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);